openapi: 3.0.0
info:
  version: 1.0.0
  title: CovidWatch API
  description: An API for submitting reports upon testing positive for covid19 fetching reports to check for contact events

paths:
  /reports:
    # GET request, to be an open endpoint for fteching reports
    get:
      description: Returns a list of reports posted since the timestamp specified
      # /reports?timestamp=<timestamp>
      parameters:
        - in: query
          name: timestamp
          schema:
            type: integer
          description: Fetch reports uploaded since timestamp
      responses:
        '200':
          description: Successfully fetched reports
          content:
            application/json:
                schema:
                  type: array
                  items:
                    type: object
                    properties:
                      tck_start:
                        type: string
                      contact_time_start:
                        type: timestamp
                      contact_time_end:
                        type: timestamp
                      memo_type:
                        type: byte
                      memo:
                        type: string
                      rvk:
                        type: object
                        # this should be implemented in JWK format specified
                        # in https://tools.ietf.org/html/rfc7517
                        # An example is below:
                        # {
                        #  "kty" : "OKP",
                        #  "crv" : "Ed25519",
                        #  "x"   : "11qYAYKxCrfVS_7TyWQHOg7hcvPapiMlrwIaaPcHURo",
                        #  "d"   : "nWGxne_9WmC6hEr0kuwsxERJxWl7MmkZcDusAxyuf2A",
                        #  "use" : "sig",
                        #  "kid" : "FdFYFzERwC2uCBB46pZQi4GG85LujR8obt-KWRBICVQ"
                        # }
                      signature:
                        type: string
                      timestamp:
                        type: timestamp
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

    post:
      description: Upload a report after positive test
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                tck_start:
                  type: string
                contact_time_start:
                  type: timestamp
                contact_time_end:
                  type: timestamp
                memo_type:
                  type: byte
                memo:
                  type: string
                rvk:
                  type: string
                signature:
                  type: string
                timestamp:
                  type: timestamp
      responses:
        '200':
          description: Successfully uploaded a report
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
