# To reduce noise and wasted github actions we only run the 1.13 linux target on
# pull requests
name: CI dev
on: [pull_request]

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.13.x]
        platform: [ubuntu-latest]
      fail-fast: false
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      - name: Install Google Cloud SDK components
        run: yes | gcloud components install beta cloud-firestore-emulator
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: cd functions && go test -v ./...
