# To reduce noise and wasted github actions we only run the 1.13 linux target on
# pull requests
name: CI dev
on: [pull_request]

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.13.x]
        platform: [ubuntu-latest]
      fail-fast: false
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Format
        # NOTE: We pipe to `tee /dev/stderr` so that any improperly formatted
        # files are logged to stderr so that they appear in the CI output.
        run: [ "$(gofmt -l $(find . -type f -name '*.go') | tee /dev/stderr)" == "" ]
      - name: Vet
        run: cd functions && go vet ./...
      - name: Test
        run: cd functions && go test ./...
